### PR TITLE
Loop back the Atrac sound when decode fail in _AtracDecodeData

### PR DESCRIPTION
**Pull request by sum2012**
Fix GTA no sound and Fix https://github.com/hrydgard/ppsspp/issues/7601
Modify log:
https://gist.github.com/sum2012/07737495cf7fd44f33ee
tag @daniel229  @hrydgard

### CODE REVIEW

**Comment by daniel229** [comment]
Good,it fixes hang issue in Silverfall.

**Comment by unknownbrackets** [comment]
What if, instead, we change this part?

```c++
					if (res == ATDECODE_FAILED) {
						// Avoid getting stuck in a loop (Virtua Tennis)
						*SamplesNum = 0;
						*finish = 1;
						*remains = 0;
						return ATRAC_ERROR_ALL_DATA_DECODED;
					}
```

Really, it shouldn't be failing, but the above may not be the most ideal thing to do if it does fail.  Above it just claims that the audio ended immediately.

Also, maybe `failedDecode` is causing problems, as I see you set it to false.  What changes if you comment out `failedDecode = true;`?

-[Unknown]

**Comment by sum2012** [comment]
The first change sound become noise
The second change ,audio cannot decode in the bike

**Comment by sum2012** [comment]
Some games don't expect ATRAC_ERROR_ALL_DATA_DECODED.
Moreover I think that it has sound memory problem as I need loop back the atrac to work correcly.

**Comment by unknownbrackets** [comment]
Does hrydgard/ppsspp#7635 take care of it?

I'd like to make it actually handle invalid data in the same way as the PSP firmware does, which I have not tested yet.  I doubt that it starts over though (or stops decoding at all e.g. like failedDecode does.)

-[Unknown]

**Comment by daniel229** [comment]
https://github.com/hrydgard/ppsspp/pull/7635 won't take care of Gripshift and Silverfall,But take care of GTA.
@sum2012 this pr causes some games(like puyopuyo fever) looping in a sound instead of silent.

**Comment by sum2012** [comment]
@daniel229 Thanks help me testing.

**Pull request closed without merging**
