### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by QWEmct**
These fucking Russophobes, they are everywhere and spoil the programs intentionally.

Look how many errors I found...

Someone's manuals will go down the drain now.
There was no need to block my account, it did not benefit the program.

I haven't been able to access the underlying repository for six years and send any pull requests, reply to comments in the bug report, etc (very strange things happen in this world))

Well, let's see what it will lead to next.
I've been trying to fix this translation for almost a month, I accidentally found out that MTX MotoTrax now works on PPSSPP and went to translate the program for myself.
I found that I can't reply to the old comments and send a request on pulling ))
Well, all right )

But it is a product that attracts many people on planet Earth... at least take it seriously... I'm not asking you to use my translation exactly, but still... there are really a lot of mistakes.
I translated it once, but few things passed the approval of the "knowledgeable" Russian language and programming terminology )
They approved only the worst of the many options and banned me )
The trolls did their job flawlessly )
They framed me and recommended the developer to encrypt the translation file in json :+1:  )))

Now the file with the translation of the program will be on the first page of my account.
And you will consider that the translation of the product that you are presenting is on top.

This is the result of hasty decisions that have not brought anything good to you or me.

----

Full translation RU #R1 27.12.2021 - the final part of the Marlezon ballet )))
The play is over, the curtain is closing, for another seven years.
I'll be back in seven years, to check )

----

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Ah, sorry, I haven't been paying much attention to pull requests on this repo.  I don't know much Russian, but I'll forward this.

-[Unknown]

**Comment by QWEmct** [comment]
> Ah, sorry, I haven't been paying much attention to pull requests on this repo. I don't know much Russian, but I'll forward this.
> 
> -[Unknown]
It's all right, it's already from 12/28.21 : https://github.com/xsacha/ppsspp/pull/1

I have sent you a new request... "Delete the nickname of the banned user" : https://github.com/unknownbrackets/ppsspp/pull/15

Since the translation is incorrect and the developer does not accept pull requests, delete my nickname.

**Comment by hrydgard** [comment]
@QWEmct I'll unban you if you promise you're gonna stay cool on the main repo - to be honest, I've forgotten why you're banned. Then you will be free to submit a proper PR instead.

**Comment by QWEmct** [comment]
@hrydgard To be honest, I'm not going to behave in any way from the word (at all). For seven years, I have only come here once to fix this squalor that you call the translation of the program. Unlike you, I am a well-mannered person (according to the norms of moral and ethical norms). I not block people in order to express solidarity with my fellow tribesmen. I don't have my own little world of program codes where I could regulate who to execute and pardon, but at the same time I don't feel violated in terms of my own self-esteem. It's not about me.

**Pull request closed without merging**
